"""Constants for speaker recognition service."""

ENV_HOST = "HOST"
ENV_PORT = "PORT"
ENV_LOG_LEVEL = "LOG_LEVEL"
ENV_ACCESS_LOG = "ACCESS_LOG"
ENV_EMBEDDINGS_DIR = "EMBEDDINGS_DIR"
ENV_API_TOKEN = "API_TOKEN"
ENV_ALLOW_INSECURE_REMOTE = "ALLOW_INSECURE_REMOTE"

DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 8099
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_ACCESS_LOG = True
DEFAULT_EMBEDDINGS_DIR = "./embeddings"
DEFAULT_API_TOKEN = ""
DEFAULT_ALLOW_INSECURE_REMOTE = False

MIN_SAMPLE_RATE = 8000
MAX_SAMPLE_RATE = 96000
MAX_AUDIO_BYTES = 12 * 1024 * 1024
MAX_AUDIO_BASE64_CHARS = ((MAX_AUDIO_BYTES + 2) // 3) * 4
MAX_TRAINING_SAMPLES = 48
MAX_TRAINING_AUDIO_BYTES = 64 * 1024 * 1024
MAX_REQUEST_BODY_BYTES = 96 * 1024 * 1024
